Langsoft.SolarSystem/Langsoft.SolarSystem/Models/Planet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace Langsoft.SolarSystem.Models
{
    [DataContract]
    public class Planet
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public Nullable<double> Mass { get; set; }
        [DataMember]
        public string MassUnit { get; set; }
        [DataMember]
        public Nullable<double> SolarDistance { get; set; }
        [DataMember]
        public string SolarDistanceUnit { get; set; }
        [DataMember]
        public Nullable<double> Diameter { get; set; }
        [DataMember]
        public string DiameterUnit { get; set; }
        [DataMember]
        public Nullable<int> NoOf_Moons { get; set; }
        [DataMember]
        public string ImageUrl { get; set; }
    }
}

Langsoft.SolarSystem/Langsoft.SolarSystem/Models/SsPlanetDetails.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Langsoft.SolarSystem.Models
{
    public class SsPlanetDetails
    {
        /// <summary>
        /// The name of this Planet.
        /// </summary>
        [DisplayName("Name: ")]
        public string Name
        {
            get;
            set;
        }

        /// <summary>
        /// The mass of this Planet.
        /// </summary>
        [DisplayName("Mass: ")]
        public string Mass
        {
            get;
            set;
        }

        /// <summary>
        /// The solar distance of this Planet.
        /// </summary>
        [DisplayName("Distance from Sun: ")]
        public string SolarDistance
        {
            get;
            set;
        }

        /// <summary>
        /// The diameter of this Planet.
        /// </summary>
        [DisplayName("Diameter: ")]
        public string Diameter
        {
            get;
            set;
        }

        /// <summary>
        /// The number of moons for this Planet.
        /// </summary>
        [DisplayName("Number of Moons: ")]
        public string NoOfMoons
        {
            get;
            set;
        }

        /// <summary>
        /// The image URL of this Planet.
        /// </summary>
        public string ImageUrl
        {
            get;
            set;
        }
    }
}

Langsoft.SolarSystem/Langsoft.SolarSystem/Models/SsPlanetVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Langsoft.SolarSystem.Models
{
    public class ssPlanetVM
    {
        public SsPlanet ssPlanet { get; set; }
        public List<SsPlanet> ssPlanetsObj { get; set; }
        public string Status
        {

            get
            {
                if (ssPlanetsObj.Count > 0)
                {
                    return "block";
                }
                else
                {
                    return "none";
                }

            }
        }//This will help us to handle the view logic

    }
}

Langsoft.SolarSystem/Langsoft.SolarSystem/Models/ssPlanet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Langsoft.SolarSystem.Models
{
    public class SsPlanet
    {
        public int PlanetID { get; set; }
        public string PlanetName { get; set; }
    }
}

Langsoft.SolarSystem/Langsoft.SolarSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Net.Http;
using System.Threading.Tasks;
using System.Text;
using Langsoft.SolarSystem.Models;
using Newtonsoft.Json;

namespace Langsoft.SolarSystem.Controllers
{
    public class HomeController : Controller
    {
        private string planetApi = ConfigurationManager.AppSettings["PlanetsAPI"];
        private HttpClient httpClient;

        public HomeController()
        {
            if (string.IsNullOrWhiteSpace(planetApi))
            {
                throw new ArgumentNullException("The Planet API url is has not been supplied.");
            }

            httpClient = new HttpClient { BaseAddress = new Uri(planetApi) };
            httpClient.DefaultRequestHeaders.Accept.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

        }
        public async Task<ActionResult> Index()
        {
            StringBuilder url = new StringBuilder();
            url.Append(planetApi);
            url.Append("/api/Planets");

            ssPlanetVM objSsPlanetVM = new ssPlanetVM();
            objSsPlanetVM.ssPlanetsObj = new List<SsPlanet>();

            List<Planet> retPlanets = null;
            HttpResponseMessage response = await httpClient.GetAsync(url.ToString());

            if (response.IsSuccessStatusCode)
            {
                var resDataString = response.Content.ReadAsStringAsync();
                retPlanets = JsonConvert.DeserializeObject<List<Planet>>(resDataString.Result);
                foreach (Planet planet in retPlanets)
                {
                    SsPlanet thePlanet = new SsPlanet()
                    {
                        PlanetID = planet.Id,
                        PlanetName = planet.Name
                    };
                    objSsPlanetVM.ssPlanetsObj.Add(thePlanet);
                }
            }

            return View(objSsPlanetVM);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Planets Application utilising Web-API";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Sorry no contact details";

            return View();
        }
    }
}

Langsoft.SolarSystem/Langsoft.SolarSystem/Controllers/PlanetDetailController.cs
using Langsoft.SolarSystem.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Langsoft.SolarSystem.Controllers
{

    public class PlanetDetailController : Controller
    {
        private string planetApi = ConfigurationManager.AppSettings["PlanetsAPI"];
        private HttpClient httpClient;

        public PlanetDetailController()
        {
            if (string.IsNullOrWhiteSpace(planetApi))
            {
                throw new ArgumentNullException("The Planet API url is has not been supplied.");
            }

            httpClient = new HttpClient { BaseAddress = new Uri(planetApi) };
            httpClient.DefaultRequestHeaders.Accept.Clear();
            httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult>PlanetDetail(string planetName)
        {

            StringBuilder url = new StringBuilder();
            url.Append(planetApi);
            url.Append("/api/Planets");
            url.Append(string.Format("?planetName={0}",planetName));

            SsPlanetDetails objSsPlanetDetails = new SsPlanetDetails();
            
            HttpResponseMessage response = await httpClient.GetAsync(url.ToString());

            if (response.IsSuccessStatusCode)
            {
                var resDataString = response.Content.ReadAsStringAsync();
                var retPlanet = JsonConvert.DeserializeObject<Planet>(resDataString.Result);

                objSsPlanetDetails.Name = retPlanet.Name;
                objSsPlanetDetails.Mass = string.Format ("{0} {1}",retPlanet.Mass.ToString(), retPlanet.MassUnit);
                objSsPlanetDetails.SolarDistance = string.Format("{0} {1}", retPlanet.SolarDistance.ToString(), retPlanet.SolarDistanceUnit);
                objSsPlanetDetails.Diameter = string.Format("{0} {1}", retPlanet.Diameter.ToString(), retPlanet.DiameterUnit);
                objSsPlanetDetails.NoOfMoons = retPlanet.NoOf_Moons.ToString();
                objSsPlanetDetails.ImageUrl = retPlanet.ImageUrl;
            }

            return View(objSsPlanetDetails);

        }
    }
}

Langsoft.SolarSystem/Langsoft.SolarSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

Langsoft.SolarSystem/Langsoft.SolarSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@*<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>*@

Langsoft.SolarSystem/Langsoft.SolarSystem/Views/Home/Index.cshtml
@model Langsoft.SolarSystem.Models.ssPlanetVM
@{
    ViewBag.Title = "Home Page";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml"; ;
}

<!DOCTYPE html>

<html>
<head>
    <style>
        .Grid-table {
            background-color: white;
            display: table;
            border: solid 1px #98BF21;
        }

        .Grid-table-table td, th {
            border: 1px solid #98BF21;
            padding: 3px 7px 2px;
        }

        .Grid-Header td th {
            background-color: #A7C942;
            color: #FFFFFF;
            text-align: left;
        }

        .Grid-alt {
            background-color: #EAF2D3;
            padding: 3px 7px 2px;
        }

        .Grid-selected {
            background-color: blue;
        }

        .Grid-rowstyle {
            padding: 3px 7px 2px;
        }

        .Grid-Footer {
            background-color: aqua;
        }
    </style>

    <script src="~/Scripts/jquery-2.1.4 (1).js"></script>

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>List of Planets (without Pluto, sorry it's no longer a planet!)</h2>
    <form id="exportWebGrid" action="Meeting/ExportHeade" method="post">
        <div name="webView" style="display:@Model.Status">

            @{
                WebGrid objWebGrid = new WebGrid(Model.ssPlanetsObj, rowsPerPage: 15, canPage: true);
            }
            @objWebGrid.GetHtml(

       tableStyle: "Grid-table",
       headerStyle: "Grid-Header",
       alternatingRowStyle: "Grid-alt",
       selectedRowStyle: "Grid-selected",
       rowStyle: "Grid-rowstyle",
       footerStyle: "Grid-Footer",
       mode: WebGridPagerModes.All, //Specifies flags that describe the methods that are provided for moving between the pages of a WebGrid instance. source msdn.microsoft.com
    columns:
       objWebGrid.Columns
       (
           @*objWebGrid.Column(columnName: "PlanetID", header: "Planet ID"),*@
           objWebGrid.Column(columnName: "PlanetName", header: "Name"),
           objWebGrid.Column(format: @<text>@Html.ActionLink("Details", "PlanetDetail", "PlanetDetail", new { planetName = item.PlanetName }, null)</text>)
        )

       )
        </div>
    </form>
</body>
</html>

Langsoft.SolarSystem/Langsoft.SolarSystem/Views/PlanetDetail/PlanetDetail.cshtml
@model Langsoft.SolarSystem.Models.SsPlanetDetails

@{
    ViewBag.Title = "Planet Detail Page";
}

@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Planet @Model.Name details</title>
</head>
<body>
    <div>
       <img src="@Url.Content(Model.ImageUrl)" alt="IMAGE" />
        <h2>Planet @Model.Name Details</h2>
        <fieldset>
            <legend>Details</legend>
            <div> @Html.LabelFor(m => m.Name) @Html.DisplayFor(m => m.Name)</div>
            <div> @Html.LabelFor(m => m.Mass) @Html.DisplayFor(m => m.Mass)</div>
            <div> @Html.LabelFor(m => m.SolarDistance) @Html.DisplayFor(m => m.SolarDistance)</div>
            <div> @Html.LabelFor(m => m.Diameter) @Html.DisplayFor(m => m.Diameter)</div>
            <div> @Html.LabelFor(m => m.NoOfMoons) @Html.DisplayFor(m => m.NoOfMoons)</div>
            @*@Html.DisplayForModel()*@
        </fieldset>
    </div>
    <input type="button" value="Back to list" onclick="location.href='@Url.Action("Index", "Home" )'" />
</body>
</html>

Langsoft.SolarSystem/Langsoft.SolarSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LangSoft Planets Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Planets", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LangSoft Planets Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>